[package]
name = "age_over_18"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
p256 = { version = "0.13", features = ["ecdsa", "serde"] }
serde_json = "1.0"
serde = "1.0"
base64ct = "1.8.0"
